kind: Deployment
apiVersion: apps/v1
metadata:
  name: auth-deployment
  labels:
    app: auth
    tier: service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
      tier: service
  template:
    metadata:
      labels:
        app: auth
        tier: service
    spec:
      containers:
      - name: auth-app
        image: zeletrik/auth-app-cn-demo:0.0.2
        ports:
        - containerPort: 3002
        imagePullPolicy: Never
        env:
        - name: JAEGER_SERVICE_NAME
          value: auth-app
        - name: JAEGER_AGENT_HOST
          value: jaeger-agent
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
---
kind: Service
apiVersion: v1
metadata:
  name: auth-service
  namespace: default
  labels:
    app: auth
    tier: service
spec:
  type: NodePort
  selector:
    app: auth
    tier: service
  ports:
  - name: api
    port: 3002
    targetPort: 3002