kind: Deployment
apiVersion: apps/v1
metadata:
  name: chain-deployment
  labels:
    app: chain
    tier: service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chain
      tier: service
  template:
    metadata:
      labels:
        app: chain
        tier: service
    spec:
      containers:
      - name: chain-app
        image: zeletrik/chain-app-cn-demo:0.0.2
        ports:
        - containerPort: 3001
        imagePullPolicy: Never
        env:
        - name: JAEGER_SERVICE_NAME
          value: chain-app
        - name: JAEGER_AGENT_HOST
          value: jaeger-agent
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
---
kind: Service
apiVersion: v1
metadata:
  name: chain-service
  namespace: default
  labels:
    app: chain
    tier: service
spec:
  type: NodePort
  selector:
    app: chain
    tier: service
  ports:
  - name: api
    port: 3001
    targetPort: 3001