---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dynamo
  labels:
    app: movie-cn-db
    tier: database
spec:
  replicas: 1 #We always want more than 1 replica
  selector:
    matchLabels:
      app: movie-cn-db
      tier: database
  template:
    metadata:
      labels:
        app: movie-cn-db
        tier: database
    spec:
      containers:
      - name: dynamo-db
        image: zeletrik/dynamodb-cn-demo:0.0.1
        ports:
        - containerPort: 8000
        imagePullPolicy: Never
      volumes:
      - name: dynamo-persistent-storage # Obtaining 'vloume' from PVC
        persistentVolumeClaim:
          claimName: dynamo-pv-claim
---
kind: Service
apiVersion: v1
metadata:
  name: dynamo-db
  namespace: default
  labels:
    app: movie-cn-db
    tier: database
spec:
  selector:
    app: movie-cn-db
    tier: database
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamo-pv-claim
  labels:
    app: movie-cn-db
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
