kind: Deployment
apiVersion: apps/v1
metadata:
  name: favorite-deployment
  labels:
    app: favorite
    tier: service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: favorite
      tier: service
  template:
    metadata:
      labels:
        app: favorite
        tier: service
    spec:
      containers:
      - name: favorite-app
        image: zeletrik/favorite-app-cn-demo:0.0.1
        ports:
        - containerPort: 3003
        imagePullPolicy: Never
        env:
        - name: JAEGER_SERVICE_NAME
          value: favorite-app
        - name: JAEGER_AGENT_HOST
          value: jaeger-agent
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
---
kind: Service
apiVersion: v1
metadata:
  name: favorite-service
  namespace: default
  labels:
    app: favorite
    tier: service
spec:
  type: NodePort
  selector:
    app: favorite
    tier: service
  ports:
  - name: api
    port: 3003
    targetPort: 3003