server:
  port: 3003

management:
  endpoints:
    metrics:
      enabled: true
    web:
      exposure:
        include: "*"
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true